### ISSUE TITLE
Platformを外部参照する

### ISSUE THREAD

**Issue by masanori1102** [masanori1102/ev3_product#1]
# Task(s)
- [] [masanori1102/ev3rt](/masanori1102/ev3rt)を platform に外部参照する
- [] hrp2/sdk/workspace を product にコピーする
- [] gitignore をコピーする
- [] Doxygen用のファイルをコピーする
- [] README.md を変更する
- [] make の設定を変更する
